import { useUser } from "@clerk/nextjs";
import type { NextPage } from "next";
import Head from "next/head";
import LoadingPage from "~/components/LoadingPage";
import { api } from "~/utils/api";

const PostDetailPage: NextPage = () => {
  const { isLoaded: userLoaded } = useUser();

  // start fetching asap.
  api.posts.getAll.useQuery();

  if (!userLoaded) return <LoadingPage />;

  return (
    <>
      <Head>
        <title>Chirp | Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center border-slate-400">
        <h1 className="text-2xl">Profile Page</h1>
      </main>
    </>
  );
};

export default PostDetailPage;
